name: AndroidCICD

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # Make sure your project supports JDK 17
          distribution: 'adopt'

      # Step 3: Build with Gradle
      - name: Build with Gradle
        run: .\gradlew build  # Windows uses .\gradlew (instead of ./gradlew on Linux/Mac)

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

                # Step 7: Upload test results
      - name: Upload test results
        uses: actions/upload-artifact@v4.4.3
        with:
                    name: test-results
                    path: app/build/test-results/testDebugUnitTest/


      # Step 4: Upload the APK build artifact
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: AndroidCICD.apk
          path: app\build\outputs\apk\debug\app-debug.apk  # Ensure this is the correct path to the APK
